import {
  Text,
  TouchableOpacity,
  Animated,
  Image,
  Dimensions,
  View,
  PermissionsAndroid,
  Linking,
  Modal,
  StyleSheet
} from "react-native";

const { width, height } = Dimensions.get("window");
const CARD_HEIGHT = height / 4;
const CARD_WIDTH = CARD_HEIGHT + 150;

export const styles = StyleSheet.create({
    infoText: {
      alignSelf: "center",
      color: "yellow",
    },
    recenterButton: {
      position: "absolute",
      alignSelf: "flex-end",
      backgroundColor: "#f7e298",
    },
    backBtn: {
      alignSelf: "center",
      color: "yellow",
      textAlign: "center",
      fontSize: 20,
      paddingBottom: 6,
      paddingTop: -2,
    },
    btnContainer: {
      marginTop: 4,
      marginLeft: 40,
      marginRight: 40,
      paddingTop: 4,
      paddingBottom: 4,
      backgroundColor: "#f7e298",
      borderRadius: 10,
      borderColor: "#fff",
      alignItems: "center",
      textAlign: "center",
    },
    btnText: {
      textAlign: "center",
      alignSelf: "center",
      color: "black",
    },
    container: {
      flex: 1,
    },
    scrollView: {
      position: "absolute",
      bottom: 20,
      left: 0,
      right: 0,
      paddingVertical: 10,
      padding: 10,
    },
    endPadding: {
      paddingRight: width - CARD_WIDTH,
    },
    card: {
      padding: 10,
      elevation: 2,
      backgroundColor: "#767bf4",
      marginHorizontal: 10,
      shadowColor: "#000",
      shadowRadius: 5,
      shadowOpacity: 0.3,
      shadowOffset: { x: 2, y: -2 },
      height: CARD_HEIGHT + 5,
      width: CARD_WIDTH - 60,
      overflow: "hidden",
      borderRadius: 25,
    },
    textContent: {
      flex: 2,
      padding: 10,
      color: "black",
    },
    cardTitle: {
      fontSize: 12,
      marginTop: 5,
      fontWeight: "bold",
      alignSelf: "center",
      color: "yellow",
    },
    cardDescription: {
      fontSize: 12,
      color: "#444",
      alignSelf: "center",
    },
    cardButtons: {
      fontSize: 24,
      alignItems: "center",
    },
    markerWrap: {
      alignItems: "center",
      justifyContent: "center",
    },
    marker: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "rgb(190, 0, 0)",
    },
    closeIcon: {
      marginTop: 10,
      marginBottom: 0,
      marginRight: -10,
      flexDirection: "row",
      fontSize: 30,
      alignItems: "center",
    },
    modalCard: {
      alignSelf: "center",
      padding: 10,
      backgroundColor: "#767bf4",
      marginTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.4,
      shadowRadius: 3,
      elevation: 1,
      height: 350,
      width: 350,
      overflow: "hidden",
      borderRadius: 10,
    },
    modalTitle: {
      alignSelf: "center",
      fontSize: 15,
      fontWeight: "bold",
      color: "yellow",
    },
    modalContent: {
      alignSelf: "center",
      marginTop: 5,
      color: "yellow",
    },
    modalBtnContainer: {
      flexDirection: "row",
      alignSelf: "center",
      alignItems: "center",
      textAlign: "center",
    },
    modalBtn: {
      margin: 10,
      width: 60,
      height: 40,
      paddingTop: 2,
      paddingBottom: 2,
      borderRadius: 10,
      backgroundColor: "#f7e298",
      borderColor: "#fff",
    },
    modalDistanceText: {
      alignSelf: "center",
      fontSize: 12,
      fontWeight: "400",
      marginTop: 2,
      color: "yellow",
    },
  });